### ISSUE TITLE
Problem running Auto Weka 2.5

### ISSUE THREAD

**Issue by PriyeshLakar** [larskotthoff/autoweka#48]
Hello team,

I am facing some problem in installing Auto Weka 2.5 on my machine. Please can you guys help me out and guide me with the same.

Steps followed:
1) Simply, downloaded the package from this website : http://www.cs.ubc.ca/labs/beta/Projects/autoweka/
2) After unzipping the package, double clicked on the autoweka.jar file.

Error : The Java JAR file "autoweka.jar" could not be launched. 
            Check the Console for possible error messages.

I am trying to install in my MAC machine, with java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11). 

Any help is highly appreciated. Thanks in advance.

**Comment by PriyeshLakar** [comment]
When I am running from the console I get this error:

LM-SJN-21011531:autoweka-2.5 plakar$ java -jar autoweka.jar 
no main manifest attribute, in autoweka.jar

Can someone please help?

**Comment by PriyeshLakar** [comment]
Just a small heads up:

I tried to do it by a new method, So I did the following steps:

1) Downloaded and installed Weka 3.8 from http://www.cs.waikato.ac.nz/ml/weka/downloading.html .
2) Downloaded the auto weka package from http://www.cs.ubc.ca/labs/beta/Projects/autoweka/ .
3) Now, after double clicking on weka-3-8-1-oracle-jvp.app the Weka Guide Chooser dialog box opens. Now, I clicked on Tools and then package manager. 
4) After the package manager dialog box opens then by clicking on File/url button under unofficial section I was able to choose and install the auto weka package by specifying the zip folder that was downloaded from step 2.
5) Now, even in installed section it does show that auto weka 2.5 is installed.
6) Finally, I go back and start explorer to use the auto weka functionality.
7) I simply uploaded the data file (iris data set) and clicked on auto-weak tab. There I clicked on Start button and this is the error which is being displayed:

Error:
Problem running auto-weka:
Java executable cannot be found. Please refer to known issues in the Auto-WEKA manual.

Any help is highly appreciated. Please guys help me out!

Thanks.

**Comment by PriyeshLakar** [comment]
Resolved. Thanks, anyway.

**Comment by larskotthoff** [comment]
Always install through the WEKA package manager, not by downloading manually.

**Comment by PriyeshLakar** [comment]
Okay, will keep that in mind @larskotthoff . Thanks.

**Comment by Bard1972** [comment]
Hi there, I did use WEKA 3.8 Tools/Package Manager for Auto WEKA 2.6but also got the same warning? Check Console for Errors? Which console? There isn't one in my download? I'm using a Mac 10.14.

Cheers!

**Comment by larskotthoff** [comment]
What's the error message you're getting and how are you running Auto-WEKA?

**Comment by Bard1972** [comment]
Hi Lars,

It says: The java file “autoweka.jar” could not be launched. Check console for errors. 

 Check console? I have no idea how to do that. Autoweka.jar is on my desktop and I downloaded it from the WEKA 3.8 s/ware via the Package Manager. WEKA 3.8 opens fine. 

I realised that I need java on this Macbook when I couldn’t get the datasets to download and tried both:

Java 8 Update 251 and
jdk-14.0.1_osx-x64_bin  (Java SE Development Kit 14)

yet neither of these either get Auto WEKA to open or the first two datasets I got from here:
https://waikato.github.io/weka-wiki/datasets/ <https://waikato.github.io/weka-wiki/datasets/>
?

I actually tried to email you yesterday at larsko@cs.ubc.ca <mailto:larsko@cs.ubc.ca> from the WEKA's homepage but it got returned? So apologies for the double attempt to reach you in the last few days but I’ve spent days trying to get this to work and am getting nowhere. 

I wanted to mimic parts of this machine learning / stock market research paper by Luke Rose who used Auto WEKA for the parameter choices (although surprisingly he used some very generic and not that reliable market indicators like the RSI and MACD etc/, instead of far more accurate signal processing indicators by people like John Ehlers: 

https://www.researchgate.net/publication/328838338_Automated_Stock_Market_Trading_Using_Machine_Learning

Cheers
Bard

**Comment by larskotthoff** [comment]
After you install Auto-WEKA with the package manager you can run it directly from WEKA -- you don't need to manually start the jar. Just open WEKA as usual; Auto-WEKA will show up as a classifier and also in a new tab that you can select.

**Comment by Bard1972** [comment]
Cheers,

To access the Classifier assumes I can open datasets. I can’t open those tutorial datasets nor my own Excel files, even when selecting CSVLoader? 
The file opener defaults to arff, is there some reason for that, am I supposed to convert my Excel files into some other format to get them to load? 

I did manage to get a text file loaded although it shows no data in it? From the Classify I now see AutoWEKAClassifier.

Thanks again,

**Comment by larskotthoff** [comment]
Hmm, sounds like a problem with WEKA. Might be better to ask them for help.

**Comment by Bard1972** [comment]
Right, 

Importing data:

I had a lot of these warnings: “Cannot determine the file loader automatically, please choose one.” 

and



Java problem?

Where should I go / who should I contact?

Cheers,

**Comment by larskotthoff** [comment]
The best place is probably the WEKA mailing list: https://waikato.github.io/weka-wiki/mailing_list/

**Comment by Bard1972** [comment]
Sorry, missed this message in my Mail. Thanks.
