### ISSUE TITLE
Is it possible to randomly run Auto-WEKA?

### ISSUE THREAD

**Issue by rbarbudo** [larskotthoff/autoweka#78]
I wonder whether it would be possible to use a random search for exploring the Auto-WEKA search space. More specifically, I would like to randomly generate pipelines consisting in two elements (feature selection and classifier/regressor) with the same WEKA algorithms and hyper-parameter space used with the SMAC algorithm. 

As far I understand, it would be necessary to create an _ExperimentConstructor_ (I think an [autoweka.ListExperimentConstructor](https://github.com/automl/autoweka/blob/master/src/java/autoweka/ListExperimentConstructor.java)) similar to the [autoweka.GridSearchExperimentConstructor](https://github.com/automl/autoweka/blob/master/src/java/autoweka/GridSearchExperimentConstructor.java). Then, this _ExperimentConstructor_ should be instantiated within the  [weka.classifiers.meta.AutoWEKAClassifier](https://github.com/automl/autoweka/blob/master/src/java/weka/classifiers/meta/AutoWEKAClassifier.java). Am I wrong?

I would really appreciate if you could give me any insight on how to develop this randomized version of Auto-WEKA. Thank you in advance for your time and the Auto-WEKA project.

**Comment by larskotthoff** [comment]
It sounds like you're on the right track. Unfortunately Auto-WEKA doesn't directly process the parameter space, but hands it to SMAC to do that. So what you have in mind wouldn't be a trivial task because you would have to assemble the parameter space from the configuration files and take dependencies into account yourself.
