### ISSUE TITLE
Help to a newbie 

### ISSUE THREAD

**Issue by delreal90** [larskotthoff/autoweka#86]
So, this post is a call for help for a project I want to do. (sorry if this is in the wrong section)

I'm a dentist and my postgraduate program thesis was about predicting the outcome for a treatment alternative. For that, I used WEKA andAuto-WEKA GUI and I achieved quite good results (we are now trying to publish the results). 

Now, I would like to share the model created with my peers, so they can try the model with their patients, in order to obtain predictions about the outcome of this therapy, but I not sure how could I share the model in a really easy way. To let you know, my programming and ML skills are 2 FutureLearn courses from Waikato University about WEKA, a 4 hours video on Youtube about python, and a lot of hours of try and error.

I think the ideal way to share the model would be a program or a website where the dentist can put the patient info, press a button and get the prediction of the chance of success of the therapy, but doing that I think that might be way above my knowledge, so what I think that might work was to have a excel file where the dentist puts the info of the patient and a python code that reads this info, using the python-weka-wrapper and autoweka (or maybe pyautoweka), in orden to test the new data using the model.

Questions:
1.- Could you please give me advise on how do you think would be the best way of action?
2.- is it possible to use autoweka with python-weka-wrapper?
3.- For what I know, pyautoweka uses less algorithms than autoweka 2.0, is there any pyautoweka 2.0?
4.- Please give me any advice you think. I'll probably have to learn anything almost from zero, so I'm OK if you tell me that I got all wrong and I should do something entirely different

Finally, what I really want is tho share our model with other dentists in the easiest way for them so they can apply this model on their patients and give them the best possible therapy. If you could guide me on how to do it, I would really appreciate that.

Thank you!!

**Comment by larskotthoff** [comment]
Hmm, the short answer is that I don't know -- I don't know what dentists are comfortable with in terms of technology, and there are probably hundreds of different ways to implement this. I haven't implemented anything like this before and can't give you any advice on that, sorry.

However, if you know that you're going to use Python with it, I'd recommend using [auto-sklearn](https://automl.github.io/auto-sklearn/master/) instead of Auto-WEKA as it's integrated natively with Python and has a few additional features (and uses the same optimization technology in the background).

I'm closing this here as it is way beyond the scope of Auto-WEKA.
