### ISSUE TITLE
Not Serializable error on trying to recall written model from AutoWeka into Weka Classifier

### ISSUE THREAD

**Issue by TonyPBF** [larskotthoff/autoweka#90]
I have been exploring AutoWeka on a smallish dataset (maybe 150x250 cells). The AutoWeka package seems to have selected a likely model to fit the data, which I wrote out to file to subsequently call into Classifier to explore prediction.

I get a NotSerializable error on the attempt, but the model wrote successfully. Those more skilled than I seem to be able to ~read~ the model - it seems intact, otherwise. 

I have been discussing this issue here: https://weka.8497.n7.nabble.com/Auto-weka-problem-td45389.html and Mike seems to be out of ideas not requiring a core update.

I am hoping the forefathers of AutoWeka may be able to help... I am willing to dredge out what data I can find.

**Comment by larskotthoff** [comment]
There's no custom serialization going on (see https://github.com/automl/autoweka/blob/master/src/java/weka/classifiers/meta/AutoWEKAClassifier.java). Auto-WEKA just hooks into the serializable interface.

**Comment by TonyPBF** [comment]
That was a guess by Mike over on Nabble. Clearly, I am no expert.

The issue persists that while AutoWeka allows a save of a generated model I cannot seem to load it back into the Weka Classifier (or workbench) due to 

java.io.WriteAbortedException. writing aborted; java.io.NotSerializableException: autoweka.ConfigurationCollection

- this is the error on attempting to load the model file in. I don't recall seeing one on the original write.
Currently running weka3.9.5 (same issue 3.8.5).

I have no custom code running here - just the Weka and AutoWeka packages. under Windows10.

IS there a helper tool or something that can fix the serialization error? I've tried to remake the model with what I see in the output window but seems there is something missing - my results on same data are unrelated to what the autoweka model yields. 

Or something?...

**Comment by larskotthoff** [comment]
Hmm, on closer inspection, this part of the code does use a custom serializer. There's a bunch of different things that could be going on. It could be the particular JRE/JDK that you're using, so trying a different one might fix it. There've been various issues with different JDKs related to the XML parser, and that might be the cause of the issue here as well. If you can, try the Oracle JDK.

**Comment by TonyPBF** [comment]
well, I've tried the version 11 bundled with the Weka download - made a mess running autoweka.
I run the weka.jar by hand from the weka 3.x.5 directory, calling the system resident 1.8.xxx JRE and paths, which gets me to the solution using AutoWeka that won't load into Classifier. So - that part may be remedied.
What JRE/JDK does AutoWeka think is 'native'? if Oracle will permit, I can try that version.
or?...
do you need my model? my last error log was some 400k - but if you want it...

**Comment by larskotthoff** [comment]
There's no particular JDK that Auto-WEKA was developed for -- at least the general idea of Java is that you write once and then run anywhere! Most issues seem to have been caused by non-Oracle JDKs. I don't have a list of JDKs that work unfortunately.

There might be an easy way around this though -- at the end of each run, Auto-WEKA prints Java code that you can use to build the best model type found in your own WEKA code. This then allows you to serialize/store any models as you like, completely independent of Auto-WEKA.

**Comment by TonyPBF** [comment]
I find myself dumbfounded that i seem to be the first human on Earth to try to use the packages as delivered (without patching together my own code) - following the instructions as written, finding this issue and am also the first to try to chase it to ground. 

OK - so there is no last known to work' configuration of versions of Weka, AutoWeka and Java JDK/JRE? Well...

I have tried to feed the results from the output buffer window back into Classifier but there is some missing context - I get totally different results suggesting I missed... something. 
Might you have a pointer to an example / tutorial of doing this extraction of said code and splicing into a java program? I was not planning to learn to code JAVA for this project (my skills are rusty - FortranIV, BASIC, Pascal...a little Prolog) but let's see. 

Easy...

**Comment by larskotthoff** [comment]
Well let me put it this way. We do test Auto-WEKA quite comprehensively, but as it turns out there are differences for different versions of JDKs, operating systems, and even WEKA. This is simply too much to test exhaustively. I can tell you that I've been using it on Linux with OpenJDK 1.8.0_282 without issues, but I don't use the serialization at all.

We also know that a lot of people have been using it successfully, and try to address any issues that are raised here, but unfortunately there's a limit to what we can do (and often even just reproducing the issue fails). This isn't meant to be an excuse, but rather an explanation -- I do realize that this is very frustrating for you!

There's an overview of how to use WEKA in your own Java code at https://waikato.github.io/weka-wiki/use_weka_in_your_java_code/

**Comment by TonyPBF** [comment]
My apologies- I wasn't trying to criticize the efforts or work outcome. 
You are correct - this is amazingly frustrating. I am running as vanilla a Win10 setup as possible. pulled the network,  antivirus, auto-updates (all) and firewall to run standalone to fix some of the prior 20-30 issues i fixed getting this far, before fiddling with many forms of data preprocessing to encourage the 'black box' to work it's magic. Which it seems to have done - if I could extract the Gold from the Black Box...
That there is not a last known good config seems a critical failing of Github - open source is not without it's issues but this seems like a pivotal item for anyone debugging anything. Maybe I should have a word with them.
And I certainly DO appreciate the combinatorics that explode out of software configurations - and of trying to diagnose intermittent issues. Which is one reason I stick with applied mechanics and other 'simpler' things. 
And I DO appreciate the time & effort.

So... This code autoweka generates is in the right side output window in the Weka frame? Or output in a file hiding somewhere?...

**Comment by larskotthoff** [comment]
Yes, it appears in the output window at the end.
