### ISSUE TITLE
"Error marshalling XML response" still unresolved

### ISSUE THREAD

**Issue by JDRomano2** [larskotthoff/autoweka#92]
Please see #87 for details. Briefly, Auto-WEKA won't run with WEKA installed with the current version of Java. 

This is still an issue with no adequate solution in place (uninstalling/reinstalling WEKA with an old, unsupported version of Java is arguably not adequate). Since Auto-WEKA is distributed in WEKA's official package manager, it really should work right out-of-the-box.

I feel that this issue should remain open until Auto-WEKA is made compatible with the current versions of WEKA and Java, even if only to give the issue visibility until a contributor is able to fix it.

**Comment by larskotthoff** [comment]
Contributions welcome :)

**Comment by eibe** [comment]
Thanks to Justin Liu, this issue has been fixed by [https://github.com/automl/autoweka/pull/93](https://github.com/automl/autoweka/pull/93) and a new Auto-WEKA package (version 2.6.3) is available in the WEKA package manager now. (Side note: Please do **not** download an Auto-WEKA 2.6 WEKA package .zip file manually from the [Auto-WEKA homepage](http://www.cs.ubc.ca/labs/beta/Projects/autoweka/) and install it via the "Unofficial" option in the WEKA package manager. Instead, simply choose Auto-WEKA from the list of packages in the WEKA package manager and click "Install". This will ensure that the correct, new version of the package is installed.)

**Comment by larskotthoff** [comment]
Thanks @eibe !
